// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_kp_502_7 (
volatile void* A_0,
volatile void* A_1,
volatile void* A_2,
volatile void* A_3,
volatile void* A_4,
volatile void* A_5,
volatile void* A_6,
volatile void* A_7,
volatile void* B_0,
volatile void* B_1,
volatile void* B_2,
volatile void* B_3,
volatile void* B_4,
volatile void* B_5,
volatile void* B_6,
volatile void* B_7,
volatile void* C_0,
volatile void* C_1,
volatile void* C_2,
volatile void* C_3,
volatile void* C_4,
volatile void* C_5,
volatile void* C_6,
volatile void* C_7,
volatile void* X1_0,
volatile void* X1_1,
volatile void* X1_2,
volatile void* X1_3,
volatile void* X1_4,
volatile void* X1_5,
volatile void* X1_6,
volatile void* X1_7,
volatile void* X2_0,
volatile void* X2_1,
volatile void* X2_2,
volatile void* X2_3,
volatile void* X2_4,
volatile void* X2_5,
volatile void* X2_6,
volatile void* X2_7,
volatile void* D_0,
volatile void* D_1,
volatile void* D_2,
volatile void* D_3,
volatile void* D_4,
volatile void* D_5,
volatile void* D_6,
volatile void* D_7);
