// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kp_502_7_kp_502_7,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-sbv484-2,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.000000,HLS_SYN_LAT=113,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=9098,HLS_SYN_LUT=8731,HLS_VERSION=2021_2}" *)

module kp_502_7 (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        B_0_address0,
        B_0_ce0,
        B_0_q0,
        B_1_address0,
        B_1_ce0,
        B_1_q0,
        B_2_address0,
        B_2_ce0,
        B_2_q0,
        B_3_address0,
        B_3_ce0,
        B_3_q0,
        C_0_address0,
        C_0_ce0,
        C_0_q0,
        C_1_address0,
        C_1_ce0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_q0,
        X1_0_address0,
        X1_0_ce0,
        X1_0_we0,
        X1_0_d0,
        X1_1_address0,
        X1_1_ce0,
        X1_1_we0,
        X1_1_d0,
        X1_2_address0,
        X1_2_ce0,
        X1_2_we0,
        X1_2_d0,
        X1_3_address0,
        X1_3_ce0,
        X1_3_we0,
        X1_3_d0,
        X2_0_address0,
        X2_0_ce0,
        X2_0_we0,
        X2_0_d0,
        X2_1_address0,
        X2_1_ce0,
        X2_1_we0,
        X2_1_d0,
        X2_2_address0,
        X2_2_ce0,
        X2_2_we0,
        X2_2_d0,
        X2_3_address0,
        X2_3_ce0,
        X2_3_we0,
        X2_3_d0,
        D_0_address0,
        D_0_ce0,
        D_0_we0,
        D_0_d0,
        D_1_address0,
        D_1_ce0,
        D_1_we0,
        D_1_d0,
        D_2_address0,
        D_2_ce0,
        D_2_we0,
        D_2_d0,
        D_3_address0,
        D_3_ce0,
        D_3_we0,
        D_3_d0
);

parameter    ap_ST_fsm_state1 = 57'd1;
parameter    ap_ST_fsm_state2 = 57'd2;
parameter    ap_ST_fsm_state3 = 57'd4;
parameter    ap_ST_fsm_state4 = 57'd8;
parameter    ap_ST_fsm_state5 = 57'd16;
parameter    ap_ST_fsm_state6 = 57'd32;
parameter    ap_ST_fsm_state7 = 57'd64;
parameter    ap_ST_fsm_state8 = 57'd128;
parameter    ap_ST_fsm_state9 = 57'd256;
parameter    ap_ST_fsm_state10 = 57'd512;
parameter    ap_ST_fsm_state11 = 57'd1024;
parameter    ap_ST_fsm_state12 = 57'd2048;
parameter    ap_ST_fsm_state13 = 57'd4096;
parameter    ap_ST_fsm_state14 = 57'd8192;
parameter    ap_ST_fsm_state15 = 57'd16384;
parameter    ap_ST_fsm_state16 = 57'd32768;
parameter    ap_ST_fsm_state17 = 57'd65536;
parameter    ap_ST_fsm_state18 = 57'd131072;
parameter    ap_ST_fsm_state19 = 57'd262144;
parameter    ap_ST_fsm_state20 = 57'd524288;
parameter    ap_ST_fsm_state21 = 57'd1048576;
parameter    ap_ST_fsm_state22 = 57'd2097152;
parameter    ap_ST_fsm_state23 = 57'd4194304;
parameter    ap_ST_fsm_state24 = 57'd8388608;
parameter    ap_ST_fsm_state25 = 57'd16777216;
parameter    ap_ST_fsm_state26 = 57'd33554432;
parameter    ap_ST_fsm_state27 = 57'd67108864;
parameter    ap_ST_fsm_state28 = 57'd134217728;
parameter    ap_ST_fsm_state29 = 57'd268435456;
parameter    ap_ST_fsm_state30 = 57'd536870912;
parameter    ap_ST_fsm_state31 = 57'd1073741824;
parameter    ap_ST_fsm_state32 = 57'd2147483648;
parameter    ap_ST_fsm_state33 = 57'd4294967296;
parameter    ap_ST_fsm_state34 = 57'd8589934592;
parameter    ap_ST_fsm_state35 = 57'd17179869184;
parameter    ap_ST_fsm_state36 = 57'd34359738368;
parameter    ap_ST_fsm_state37 = 57'd68719476736;
parameter    ap_ST_fsm_state38 = 57'd137438953472;
parameter    ap_ST_fsm_state39 = 57'd274877906944;
parameter    ap_ST_fsm_state40 = 57'd549755813888;
parameter    ap_ST_fsm_state41 = 57'd1099511627776;
parameter    ap_ST_fsm_state42 = 57'd2199023255552;
parameter    ap_ST_fsm_state43 = 57'd4398046511104;
parameter    ap_ST_fsm_state44 = 57'd8796093022208;
parameter    ap_ST_fsm_state45 = 57'd17592186044416;
parameter    ap_ST_fsm_state46 = 57'd35184372088832;
parameter    ap_ST_fsm_state47 = 57'd70368744177664;
parameter    ap_ST_fsm_state48 = 57'd140737488355328;
parameter    ap_ST_fsm_state49 = 57'd281474976710656;
parameter    ap_ST_fsm_state50 = 57'd562949953421312;
parameter    ap_ST_fsm_state51 = 57'd1125899906842624;
parameter    ap_ST_fsm_state52 = 57'd2251799813685248;
parameter    ap_ST_fsm_state53 = 57'd4503599627370496;
parameter    ap_ST_fsm_state54 = 57'd9007199254740992;
parameter    ap_ST_fsm_state55 = 57'd18014398509481984;
parameter    ap_ST_fsm_state56 = 57'd36028797018963968;
parameter    ap_ST_fsm_state57 = 57'd72057594037927936;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
output  [0:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
output  [0:0] A_2_address0;
output   A_2_ce0;
input  [31:0] A_2_q0;
output  [0:0] A_3_address0;
output   A_3_ce0;
input  [31:0] A_3_q0;
output  [0:0] B_0_address0;
output   B_0_ce0;
input  [31:0] B_0_q0;
output  [0:0] B_1_address0;
output   B_1_ce0;
input  [31:0] B_1_q0;
output  [0:0] B_2_address0;
output   B_2_ce0;
input  [31:0] B_2_q0;
output  [0:0] B_3_address0;
output   B_3_ce0;
input  [31:0] B_3_q0;
output  [0:0] C_0_address0;
output   C_0_ce0;
input  [31:0] C_0_q0;
output  [0:0] C_1_address0;
output   C_1_ce0;
input  [31:0] C_1_q0;
output  [0:0] C_2_address0;
output   C_2_ce0;
input  [31:0] C_2_q0;
output  [0:0] C_3_address0;
output   C_3_ce0;
input  [31:0] C_3_q0;
output  [0:0] X1_0_address0;
output   X1_0_ce0;
output   X1_0_we0;
output  [31:0] X1_0_d0;
output  [0:0] X1_1_address0;
output   X1_1_ce0;
output   X1_1_we0;
output  [31:0] X1_1_d0;
output  [0:0] X1_2_address0;
output   X1_2_ce0;
output   X1_2_we0;
output  [31:0] X1_2_d0;
output  [0:0] X1_3_address0;
output   X1_3_ce0;
output   X1_3_we0;
output  [31:0] X1_3_d0;
output  [0:0] X2_0_address0;
output   X2_0_ce0;
output   X2_0_we0;
output  [31:0] X2_0_d0;
output  [0:0] X2_1_address0;
output   X2_1_ce0;
output   X2_1_we0;
output  [31:0] X2_1_d0;
output  [0:0] X2_2_address0;
output   X2_2_ce0;
output   X2_2_we0;
output  [31:0] X2_2_d0;
output  [0:0] X2_3_address0;
output   X2_3_ce0;
output   X2_3_we0;
output  [31:0] X2_3_d0;
output  [0:0] D_0_address0;
output   D_0_ce0;
output   D_0_we0;
output  [31:0] D_0_d0;
output  [0:0] D_1_address0;
output   D_1_ce0;
output   D_1_we0;
output  [31:0] D_1_d0;
output  [0:0] D_2_address0;
output   D_2_ce0;
output   D_2_we0;
output  [31:0] D_2_d0;
output  [0:0] D_3_address0;
output   D_3_ce0;
output   D_3_we0;
output  [31:0] D_3_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg A_0_ce0;
reg A_1_ce0;
reg A_2_ce0;
reg A_3_ce0;
reg B_0_ce0;
reg B_1_ce0;
reg B_2_ce0;
reg B_3_ce0;
reg C_0_ce0;
reg C_1_ce0;
reg C_2_ce0;
reg C_3_ce0;
reg X1_0_ce0;
reg X1_0_we0;
reg X1_1_ce0;
reg X1_1_we0;
reg X1_2_ce0;
reg X1_2_we0;
reg X1_3_ce0;
reg X1_3_we0;
reg X2_0_ce0;
reg X2_0_we0;
reg X2_1_ce0;
reg X2_1_we0;
reg X2_2_ce0;
reg X2_2_we0;
reg X2_3_ce0;
reg X2_3_we0;
reg D_0_ce0;
reg D_0_we0;
reg D_1_ce0;
reg D_1_we0;
reg D_2_ce0;
reg D_2_we0;
reg D_3_ce0;
reg D_3_we0;

(* fsm_encoding = "none" *) reg   [56:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] zext_ln9_fu_448_p1;
reg   [63:0] zext_ln9_reg_697;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_fu_432_p3;
reg  signed [31:0] temp_B_reg_773;
wire    ap_CS_fsm_state3;
reg  signed [31:0] temp_A_reg_781;
reg  signed [31:0] C_0_load_reg_787;
reg  signed [31:0] temp_B_1_reg_792;
reg  signed [31:0] temp_A_1_reg_800;
reg  signed [31:0] C_1_load_reg_806;
reg  signed [31:0] temp_B_2_reg_811;
reg  signed [31:0] temp_A_2_reg_819;
reg  signed [31:0] C_2_load_reg_825;
reg  signed [31:0] temp_B_3_reg_830;
reg  signed [31:0] temp_A_3_reg_838;
reg  signed [31:0] C_3_load_reg_844;
wire   [31:0] grp_fu_475_p2;
reg   [31:0] mul_ln13_reg_849;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_479_p2;
reg   [31:0] mul_ln13_1_reg_854;
wire   [31:0] grp_fu_483_p2;
reg   [31:0] mul_ln13_2_reg_859;
wire   [31:0] grp_fu_487_p2;
reg   [31:0] mul_ln13_3_reg_864;
wire   [31:0] grp_fu_491_p2;
reg   [31:0] mul_ln13_4_reg_869;
wire   [31:0] grp_fu_495_p2;
reg   [31:0] mul_ln13_5_reg_874;
wire   [31:0] grp_fu_499_p2;
reg   [31:0] mul_ln13_6_reg_879;
wire   [31:0] grp_fu_503_p2;
reg   [31:0] mul_ln13_7_reg_884;
wire   [31:0] xf_V_fu_512_p2;
reg   [31:0] xf_V_reg_889;
wire    ap_CS_fsm_state7;
wire   [31:0] xf_V_1_fu_523_p2;
reg   [31:0] xf_V_1_reg_894;
wire   [31:0] xf_V_2_fu_534_p2;
reg   [31:0] xf_V_2_reg_899;
wire   [31:0] xf_V_3_fu_545_p2;
reg   [31:0] xf_V_3_reg_904;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_404_ap_return;
reg   [15:0] p_Val2_s_reg_909;
wire    ap_CS_fsm_state19;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_409_ap_return;
reg   [15:0] p_Val2_33_reg_914;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_414_ap_return;
reg   [15:0] p_Val2_34_reg_919;
wire   [15:0] grp_sqrt_fixed_32_32_s_fu_419_ap_return;
reg   [15:0] p_Val2_35_reg_924;
wire   [31:0] add_ln19_fu_554_p2;
reg   [31:0] add_ln19_reg_929;
wire    ap_CS_fsm_state20;
wire   [31:0] sub_ln20_fu_559_p2;
reg   [31:0] sub_ln20_reg_934;
wire   [31:0] add_ln19_1_fu_567_p2;
reg   [31:0] add_ln19_1_reg_939;
wire   [31:0] sub_ln20_1_fu_572_p2;
reg   [31:0] sub_ln20_1_reg_944;
wire   [31:0] add_ln19_2_fu_580_p2;
reg   [31:0] add_ln19_2_reg_949;
wire   [31:0] sub_ln20_2_fu_585_p2;
reg   [31:0] sub_ln20_2_reg_954;
wire   [31:0] add_ln19_3_fu_593_p2;
reg   [31:0] add_ln19_3_reg_959;
wire   [31:0] sub_ln20_3_fu_598_p2;
reg   [31:0] sub_ln20_3_reg_964;
wire   [31:0] shl_ln19_fu_603_p2;
wire    ap_CS_fsm_state21;
wire   [31:0] shl_ln19_1_fu_618_p2;
wire   [31:0] shl_ln19_2_fu_633_p2;
wire   [31:0] shl_ln19_3_fu_648_p2;
wire   [31:0] grp_fu_608_p2;
reg   [31:0] sdiv_ln19_1_reg_993;
wire    ap_CS_fsm_state56;
wire   [31:0] grp_fu_613_p2;
reg   [31:0] sdiv_ln20_reg_998;
wire   [31:0] grp_fu_623_p2;
reg   [31:0] sdiv_ln19_reg_1003;
wire   [31:0] grp_fu_628_p2;
reg   [31:0] sdiv_ln20_1_reg_1008;
wire   [31:0] grp_fu_638_p2;
reg   [31:0] sdiv_ln19_2_reg_1013;
wire   [31:0] grp_fu_643_p2;
reg   [31:0] sdiv_ln20_2_reg_1018;
wire   [31:0] grp_fu_653_p2;
reg   [31:0] sdiv_ln19_3_reg_1023;
wire   [31:0] grp_fu_658_p2;
reg   [31:0] sdiv_ln20_3_reg_1028;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state57;
reg   [3:0] i_fu_88;
wire   [3:0] add_ln8_fu_464_p2;
wire   [0:0] tmp_34_fu_440_p3;
wire    ap_CS_fsm_state4;
wire   [31:0] shl_ln13_fu_507_p2;
wire   [31:0] shl_ln13_1_fu_518_p2;
wire   [31:0] shl_ln13_2_fu_529_p2;
wire   [31:0] shl_ln13_3_fu_540_p2;
wire   [31:0] zext_ln840_fu_551_p1;
wire   [31:0] zext_ln840_1_fu_564_p1;
wire   [31:0] zext_ln840_2_fu_577_p1;
wire   [31:0] zext_ln840_3_fu_590_p1;
reg    grp_fu_608_ap_start;
wire    grp_fu_608_ap_done;
reg    grp_fu_613_ap_start;
wire    grp_fu_613_ap_done;
reg    grp_fu_623_ap_start;
wire    grp_fu_623_ap_done;
reg    grp_fu_628_ap_start;
wire    grp_fu_628_ap_done;
reg    grp_fu_638_ap_start;
wire    grp_fu_638_ap_done;
reg    grp_fu_643_ap_start;
wire    grp_fu_643_ap_done;
reg    grp_fu_653_ap_start;
wire    grp_fu_653_ap_done;
reg    grp_fu_658_ap_start;
wire    grp_fu_658_ap_done;
reg   [56:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 57'd1;
end

kp_502_7_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_404(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xf_V_reg_889),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_404_ap_return)
);

kp_502_7_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_409(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xf_V_1_reg_894),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_409_ap_return)
);

kp_502_7_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_414(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xf_V_2_reg_899),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_414_ap_return)
);

kp_502_7_sqrt_fixed_32_32_s grp_sqrt_fixed_32_32_s_fu_419(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(xf_V_3_reg_904),
    .ap_return(grp_sqrt_fixed_32_32_s_fu_419_ap_return)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_B_reg_773),
    .din1(temp_B_reg_773),
    .ce(1'b1),
    .dout(grp_fu_475_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_A_reg_781),
    .din1(C_0_load_reg_787),
    .ce(1'b1),
    .dout(grp_fu_479_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_B_1_reg_792),
    .din1(temp_B_1_reg_792),
    .ce(1'b1),
    .dout(grp_fu_483_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_A_1_reg_800),
    .din1(C_1_load_reg_806),
    .ce(1'b1),
    .dout(grp_fu_487_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_B_2_reg_811),
    .din1(temp_B_2_reg_811),
    .ce(1'b1),
    .dout(grp_fu_491_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_A_2_reg_819),
    .din1(C_2_load_reg_825),
    .ce(1'b1),
    .dout(grp_fu_495_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_B_3_reg_830),
    .din1(temp_B_3_reg_830),
    .ce(1'b1),
    .dout(grp_fu_499_p2)
);

kp_502_7_mul_32s_32s_32_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_3_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(temp_A_3_reg_838),
    .din1(C_3_load_reg_844),
    .ce(1'b1),
    .dout(grp_fu_503_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_608_ap_start),
    .done(grp_fu_608_ap_done),
    .din0(add_ln19_reg_929),
    .din1(shl_ln19_fu_603_p2),
    .ce(1'b1),
    .dout(grp_fu_608_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_613_ap_start),
    .done(grp_fu_613_ap_done),
    .din0(sub_ln20_reg_934),
    .din1(shl_ln19_fu_603_p2),
    .ce(1'b1),
    .dout(grp_fu_613_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_623_ap_start),
    .done(grp_fu_623_ap_done),
    .din0(add_ln19_1_reg_939),
    .din1(shl_ln19_1_fu_618_p2),
    .ce(1'b1),
    .dout(grp_fu_623_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_628_ap_start),
    .done(grp_fu_628_ap_done),
    .din0(sub_ln20_1_reg_944),
    .din1(shl_ln19_1_fu_618_p2),
    .ce(1'b1),
    .dout(grp_fu_628_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_638_ap_start),
    .done(grp_fu_638_ap_done),
    .din0(add_ln19_2_reg_949),
    .din1(shl_ln19_2_fu_633_p2),
    .ce(1'b1),
    .dout(grp_fu_638_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_643_ap_start),
    .done(grp_fu_643_ap_done),
    .din0(sub_ln20_2_reg_954),
    .din1(shl_ln19_2_fu_633_p2),
    .ce(1'b1),
    .dout(grp_fu_643_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_653_ap_start),
    .done(grp_fu_653_ap_done),
    .din0(add_ln19_3_reg_959),
    .din1(shl_ln19_3_fu_648_p2),
    .ce(1'b1),
    .dout(grp_fu_653_p2)
);

kp_502_7_sdiv_32ns_32ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_seq_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_658_ap_start),
    .done(grp_fu_658_ap_done),
    .din0(sub_ln20_3_reg_964),
    .din1(shl_ln19_3_fu_648_p2),
    .ce(1'b1),
    .dout(grp_fu_658_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_88 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_432_p3 == 1'd0))) begin
        i_fu_88 <= add_ln8_fu_464_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        C_0_load_reg_787 <= C_0_q0;
        C_1_load_reg_806 <= C_1_q0;
        C_2_load_reg_825 <= C_2_q0;
        C_3_load_reg_844 <= C_3_q0;
        temp_A_1_reg_800 <= A_1_q0;
        temp_A_2_reg_819 <= A_2_q0;
        temp_A_3_reg_838 <= A_3_q0;
        temp_A_reg_781 <= A_0_q0;
        temp_B_1_reg_792 <= B_1_q0;
        temp_B_2_reg_811 <= B_2_q0;
        temp_B_3_reg_830 <= B_3_q0;
        temp_B_reg_773 <= B_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln19_1_reg_939 <= add_ln19_1_fu_567_p2;
        add_ln19_2_reg_949 <= add_ln19_2_fu_580_p2;
        add_ln19_3_reg_959 <= add_ln19_3_fu_593_p2;
        add_ln19_reg_929 <= add_ln19_fu_554_p2;
        sub_ln20_1_reg_944 <= sub_ln20_1_fu_572_p2;
        sub_ln20_2_reg_954 <= sub_ln20_2_fu_585_p2;
        sub_ln20_3_reg_964 <= sub_ln20_3_fu_598_p2;
        sub_ln20_reg_934 <= sub_ln20_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln13_1_reg_854 <= grp_fu_479_p2;
        mul_ln13_2_reg_859 <= grp_fu_483_p2;
        mul_ln13_3_reg_864 <= grp_fu_487_p2;
        mul_ln13_4_reg_869 <= grp_fu_491_p2;
        mul_ln13_5_reg_874 <= grp_fu_495_p2;
        mul_ln13_6_reg_879 <= grp_fu_499_p2;
        mul_ln13_7_reg_884 <= grp_fu_503_p2;
        mul_ln13_reg_849 <= grp_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        p_Val2_33_reg_914 <= grp_sqrt_fixed_32_32_s_fu_409_ap_return;
        p_Val2_34_reg_919 <= grp_sqrt_fixed_32_32_s_fu_414_ap_return;
        p_Val2_35_reg_924 <= grp_sqrt_fixed_32_32_s_fu_419_ap_return;
        p_Val2_s_reg_909 <= grp_sqrt_fixed_32_32_s_fu_404_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        sdiv_ln19_1_reg_993 <= grp_fu_608_p2;
        sdiv_ln19_2_reg_1013 <= grp_fu_638_p2;
        sdiv_ln19_3_reg_1023 <= grp_fu_653_p2;
        sdiv_ln19_reg_1003 <= grp_fu_623_p2;
        sdiv_ln20_1_reg_1008 <= grp_fu_628_p2;
        sdiv_ln20_2_reg_1018 <= grp_fu_643_p2;
        sdiv_ln20_3_reg_1028 <= grp_fu_658_p2;
        sdiv_ln20_reg_998 <= grp_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xf_V_1_reg_894 <= xf_V_1_fu_523_p2;
        xf_V_2_reg_899 <= xf_V_2_fu_534_p2;
        xf_V_3_reg_904 <= xf_V_3_fu_545_p2;
        xf_V_reg_889 <= xf_V_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_432_p3 == 1'd0))) begin
        zext_ln9_reg_697[0] <= zext_ln9_fu_448_p1[0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_0_ce0 = 1'b1;
    end else begin
        A_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_2_ce0 = 1'b1;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        A_3_ce0 = 1'b1;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_0_ce0 = 1'b1;
    end else begin
        B_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_1_ce0 = 1'b1;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_2_ce0 = 1'b1;
    end else begin
        B_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B_3_ce0 = 1'b1;
    end else begin
        B_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_0_ce0 = 1'b1;
    end else begin
        C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_1_ce0 = 1'b1;
    end else begin
        C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_2_ce0 = 1'b1;
    end else begin
        C_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        C_3_ce0 = 1'b1;
    end else begin
        C_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_0_ce0 = 1'b1;
    end else begin
        D_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_0_we0 = 1'b1;
    end else begin
        D_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_1_ce0 = 1'b1;
    end else begin
        D_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_1_we0 = 1'b1;
    end else begin
        D_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_2_ce0 = 1'b1;
    end else begin
        D_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_2_we0 = 1'b1;
    end else begin
        D_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_3_ce0 = 1'b1;
    end else begin
        D_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        D_3_we0 = 1'b1;
    end else begin
        D_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_0_ce0 = 1'b1;
    end else begin
        X1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_0_we0 = 1'b1;
    end else begin
        X1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_1_ce0 = 1'b1;
    end else begin
        X1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_1_we0 = 1'b1;
    end else begin
        X1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_2_ce0 = 1'b1;
    end else begin
        X1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_2_we0 = 1'b1;
    end else begin
        X1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_3_ce0 = 1'b1;
    end else begin
        X1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X1_3_we0 = 1'b1;
    end else begin
        X1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_0_ce0 = 1'b1;
    end else begin
        X2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_0_we0 = 1'b1;
    end else begin
        X2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_1_ce0 = 1'b1;
    end else begin
        X2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_1_we0 = 1'b1;
    end else begin
        X2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_2_ce0 = 1'b1;
    end else begin
        X2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_2_we0 = 1'b1;
    end else begin
        X2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_3_ce0 = 1'b1;
    end else begin
        X2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        X2_3_we0 = 1'b1;
    end else begin
        X2_3_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_432_p3 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_432_p3 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_608_ap_start = 1'b1;
    end else begin
        grp_fu_608_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_613_ap_start = 1'b1;
    end else begin
        grp_fu_613_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_623_ap_start = 1'b1;
    end else begin
        grp_fu_623_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_628_ap_start = 1'b1;
    end else begin
        grp_fu_628_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_638_ap_start = 1'b1;
    end else begin
        grp_fu_638_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_643_ap_start = 1'b1;
    end else begin
        grp_fu_643_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_653_ap_start = 1'b1;
    end else begin
        grp_fu_653_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_658_ap_start = 1'b1;
    end else begin
        grp_fu_658_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_432_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = zext_ln9_fu_448_p1;

assign A_1_address0 = zext_ln9_fu_448_p1;

assign A_2_address0 = zext_ln9_fu_448_p1;

assign A_3_address0 = zext_ln9_fu_448_p1;

assign B_0_address0 = zext_ln9_fu_448_p1;

assign B_1_address0 = zext_ln9_fu_448_p1;

assign B_2_address0 = zext_ln9_fu_448_p1;

assign B_3_address0 = zext_ln9_fu_448_p1;

assign C_0_address0 = zext_ln9_fu_448_p1;

assign C_1_address0 = zext_ln9_fu_448_p1;

assign C_2_address0 = zext_ln9_fu_448_p1;

assign C_3_address0 = zext_ln9_fu_448_p1;

assign D_0_address0 = zext_ln9_reg_697;

assign D_0_d0 = (mul_ln13_reg_849 - shl_ln13_fu_507_p2);

assign D_1_address0 = zext_ln9_reg_697;

assign D_1_d0 = (mul_ln13_2_reg_859 - shl_ln13_1_fu_518_p2);

assign D_2_address0 = zext_ln9_reg_697;

assign D_2_d0 = (mul_ln13_4_reg_869 - shl_ln13_2_fu_529_p2);

assign D_3_address0 = zext_ln9_reg_697;

assign D_3_d0 = (mul_ln13_6_reg_879 - shl_ln13_3_fu_540_p2);

assign X1_0_address0 = zext_ln9_reg_697;

assign X1_0_d0 = (32'd0 - sdiv_ln19_1_reg_993);

assign X1_1_address0 = zext_ln9_reg_697;

assign X1_1_d0 = (32'd0 - sdiv_ln19_reg_1003);

assign X1_2_address0 = zext_ln9_reg_697;

assign X1_2_d0 = (32'd0 - sdiv_ln19_2_reg_1013);

assign X1_3_address0 = zext_ln9_reg_697;

assign X1_3_d0 = (32'd0 - sdiv_ln19_3_reg_1023);

assign X2_0_address0 = zext_ln9_reg_697;

assign X2_0_d0 = sdiv_ln20_reg_998;

assign X2_1_address0 = zext_ln9_reg_697;

assign X2_1_d0 = sdiv_ln20_1_reg_1008;

assign X2_2_address0 = zext_ln9_reg_697;

assign X2_2_d0 = sdiv_ln20_2_reg_1018;

assign X2_3_address0 = zext_ln9_reg_697;

assign X2_3_d0 = sdiv_ln20_3_reg_1028;

assign add_ln19_1_fu_567_p2 = ($signed(temp_B_1_reg_792) + $signed(zext_ln840_1_fu_564_p1));

assign add_ln19_2_fu_580_p2 = ($signed(temp_B_2_reg_811) + $signed(zext_ln840_2_fu_577_p1));

assign add_ln19_3_fu_593_p2 = ($signed(temp_B_3_reg_830) + $signed(zext_ln840_3_fu_590_p1));

assign add_ln19_fu_554_p2 = ($signed(temp_B_reg_773) + $signed(zext_ln840_fu_551_p1));

assign add_ln8_fu_464_p2 = (i_fu_88 + 4'd4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign shl_ln13_1_fu_518_p2 = mul_ln13_3_reg_864 << 32'd2;

assign shl_ln13_2_fu_529_p2 = mul_ln13_5_reg_874 << 32'd2;

assign shl_ln13_3_fu_540_p2 = mul_ln13_7_reg_884 << 32'd2;

assign shl_ln13_fu_507_p2 = mul_ln13_1_reg_854 << 32'd2;

assign shl_ln19_1_fu_618_p2 = temp_A_1_reg_800 << 32'd1;

assign shl_ln19_2_fu_633_p2 = temp_A_2_reg_819 << 32'd1;

assign shl_ln19_3_fu_648_p2 = temp_A_3_reg_838 << 32'd1;

assign shl_ln19_fu_603_p2 = temp_A_reg_781 << 32'd1;

assign sub_ln20_1_fu_572_p2 = ($signed(zext_ln840_1_fu_564_p1) - $signed(temp_B_1_reg_792));

assign sub_ln20_2_fu_585_p2 = ($signed(zext_ln840_2_fu_577_p1) - $signed(temp_B_2_reg_811));

assign sub_ln20_3_fu_598_p2 = ($signed(zext_ln840_3_fu_590_p1) - $signed(temp_B_3_reg_830));

assign sub_ln20_fu_559_p2 = ($signed(zext_ln840_fu_551_p1) - $signed(temp_B_reg_773));

assign tmp_34_fu_440_p3 = i_fu_88[32'd2];

assign tmp_fu_432_p3 = i_fu_88[32'd3];

assign xf_V_1_fu_523_p2 = (mul_ln13_2_reg_859 - shl_ln13_1_fu_518_p2);

assign xf_V_2_fu_534_p2 = (mul_ln13_4_reg_869 - shl_ln13_2_fu_529_p2);

assign xf_V_3_fu_545_p2 = (mul_ln13_6_reg_879 - shl_ln13_3_fu_540_p2);

assign xf_V_fu_512_p2 = (mul_ln13_reg_849 - shl_ln13_fu_507_p2);

assign zext_ln840_1_fu_564_p1 = p_Val2_33_reg_914;

assign zext_ln840_2_fu_577_p1 = p_Val2_34_reg_919;

assign zext_ln840_3_fu_590_p1 = p_Val2_35_reg_924;

assign zext_ln840_fu_551_p1 = p_Val2_s_reg_909;

assign zext_ln9_fu_448_p1 = tmp_34_fu_440_p3;

always @ (posedge ap_clk) begin
    zext_ln9_reg_697[63:1] <= 63'b000000000000000000000000000000000000000000000000000000000000000;
end

endmodule //kp_502_7
