// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lab4_z2_lab4_z2,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-csg325-1Q,HLS_INPUT_CLOCK=14.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=10.622000,HLS_SYN_LAT=51,HLS_SYN_TPT=50,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=295,HLS_SYN_LUT=456,HLS_VERSION=2021_2}" *)

module lab4_z2 (
        ap_local_block,
        ap_local_deadlock,
        data_in_address0,
        data_in_ce0,
        data_in_d0,
        data_in_q0,
        data_in_we0,
        data_in_address1,
        data_in_ce1,
        data_in_d1,
        data_in_q1,
        data_in_we1,
        scale,
        data_out1_address0,
        data_out1_ce0,
        data_out1_d0,
        data_out1_q0,
        data_out1_we0,
        data_out1_address1,
        data_out1_ce1,
        data_out1_d1,
        data_out1_q1,
        data_out1_we1,
        data_out2_address0,
        data_out2_ce0,
        data_out2_d0,
        data_out2_q0,
        data_out2_we0,
        data_out2_address1,
        data_out2_ce1,
        data_out2_d1,
        data_out2_q1,
        data_out2_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output   ap_local_block;
output   ap_local_deadlock;
output  [3:0] data_in_address0;
output   data_in_ce0;
output  [31:0] data_in_d0;
input  [31:0] data_in_q0;
output   data_in_we0;
output  [3:0] data_in_address1;
output   data_in_ce1;
output  [31:0] data_in_d1;
input  [31:0] data_in_q1;
output   data_in_we1;
input  [31:0] scale;
output  [3:0] data_out1_address0;
output   data_out1_ce0;
output  [31:0] data_out1_d0;
input  [31:0] data_out1_q0;
output   data_out1_we0;
output  [3:0] data_out1_address1;
output   data_out1_ce1;
output  [31:0] data_out1_d1;
input  [31:0] data_out1_q1;
output   data_out1_we1;
output  [3:0] data_out2_address0;
output   data_out2_ce0;
output  [31:0] data_out2_d0;
input  [31:0] data_out2_q0;
output   data_out2_we0;
output  [3:0] data_out2_address1;
output   data_out2_ce1;
output  [31:0] data_out2_d1;
input  [31:0] data_out2_q1;
output   data_out2_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Loop_Loop1_proc_U0_ap_start;
wire    Loop_Loop1_proc_U0_start_full_n;
wire    Loop_Loop1_proc_U0_ap_done;
wire    Loop_Loop1_proc_U0_ap_continue;
wire    Loop_Loop1_proc_U0_ap_idle;
wire    Loop_Loop1_proc_U0_ap_ready;
wire    Loop_Loop1_proc_U0_start_out;
wire    Loop_Loop1_proc_U0_start_write;
wire   [3:0] Loop_Loop1_proc_U0_data_in_address0;
wire    Loop_Loop1_proc_U0_data_in_ce0;
wire   [31:0] Loop_Loop1_proc_U0_tempA1_din;
wire    Loop_Loop1_proc_U0_tempA1_write;
wire   [31:0] Loop_Loop1_proc_U0_tempA2_din;
wire    Loop_Loop1_proc_U0_tempA2_write;
wire    Loop_Loop2_proc_U0_ap_start;
wire    Loop_Loop2_proc_U0_ap_done;
wire    Loop_Loop2_proc_U0_ap_continue;
wire    Loop_Loop2_proc_U0_ap_idle;
wire    Loop_Loop2_proc_U0_ap_ready;
wire    Loop_Loop2_proc_U0_tempA1_read;
wire   [3:0] Loop_Loop2_proc_U0_data_out1_address0;
wire    Loop_Loop2_proc_U0_data_out1_ce0;
wire    Loop_Loop2_proc_U0_data_out1_we0;
wire   [31:0] Loop_Loop2_proc_U0_data_out1_d0;
wire    Loop_Loop3_proc_U0_ap_start;
wire    Loop_Loop3_proc_U0_ap_done;
wire    Loop_Loop3_proc_U0_ap_continue;
wire    Loop_Loop3_proc_U0_ap_idle;
wire    Loop_Loop3_proc_U0_ap_ready;
wire    Loop_Loop3_proc_U0_tempA2_read;
wire   [3:0] Loop_Loop3_proc_U0_data_out2_address0;
wire    Loop_Loop3_proc_U0_data_out2_ce0;
wire    Loop_Loop3_proc_U0_data_out2_we0;
wire   [31:0] Loop_Loop3_proc_U0_data_out2_d0;
wire    tempA1_full_n;
wire   [31:0] tempA1_dout;
wire    tempA1_empty_n;
wire    tempA2_full_n;
wire   [31:0] tempA2_dout;
wire    tempA2_empty_n;
wire    ap_sync_done;
wire   [0:0] start_for_Loop_Loop2_proc_U0_din;
wire    start_for_Loop_Loop2_proc_U0_full_n;
wire   [0:0] start_for_Loop_Loop2_proc_U0_dout;
wire    start_for_Loop_Loop2_proc_U0_empty_n;
wire   [0:0] start_for_Loop_Loop3_proc_U0_din;
wire    start_for_Loop_Loop3_proc_U0_full_n;
wire   [0:0] start_for_Loop_Loop3_proc_U0_dout;
wire    start_for_Loop_Loop3_proc_U0_empty_n;

lab4_z2_Loop_Loop1_proc Loop_Loop1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop1_proc_U0_ap_start),
    .start_full_n(Loop_Loop1_proc_U0_start_full_n),
    .ap_done(Loop_Loop1_proc_U0_ap_done),
    .ap_continue(Loop_Loop1_proc_U0_ap_continue),
    .ap_idle(Loop_Loop1_proc_U0_ap_idle),
    .ap_ready(Loop_Loop1_proc_U0_ap_ready),
    .start_out(Loop_Loop1_proc_U0_start_out),
    .start_write(Loop_Loop1_proc_U0_start_write),
    .data_in_address0(Loop_Loop1_proc_U0_data_in_address0),
    .data_in_ce0(Loop_Loop1_proc_U0_data_in_ce0),
    .data_in_q0(data_in_q0),
    .scale(scale),
    .tempA1_din(Loop_Loop1_proc_U0_tempA1_din),
    .tempA1_full_n(tempA1_full_n),
    .tempA1_write(Loop_Loop1_proc_U0_tempA1_write),
    .tempA2_din(Loop_Loop1_proc_U0_tempA2_din),
    .tempA2_full_n(tempA2_full_n),
    .tempA2_write(Loop_Loop1_proc_U0_tempA2_write)
);

lab4_z2_Loop_Loop2_proc Loop_Loop2_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop2_proc_U0_ap_start),
    .ap_done(Loop_Loop2_proc_U0_ap_done),
    .ap_continue(Loop_Loop2_proc_U0_ap_continue),
    .ap_idle(Loop_Loop2_proc_U0_ap_idle),
    .ap_ready(Loop_Loop2_proc_U0_ap_ready),
    .tempA1_dout(tempA1_dout),
    .tempA1_empty_n(tempA1_empty_n),
    .tempA1_read(Loop_Loop2_proc_U0_tempA1_read),
    .data_out1_address0(Loop_Loop2_proc_U0_data_out1_address0),
    .data_out1_ce0(Loop_Loop2_proc_U0_data_out1_ce0),
    .data_out1_we0(Loop_Loop2_proc_U0_data_out1_we0),
    .data_out1_d0(Loop_Loop2_proc_U0_data_out1_d0)
);

lab4_z2_Loop_Loop3_proc Loop_Loop3_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_Loop3_proc_U0_ap_start),
    .ap_done(Loop_Loop3_proc_U0_ap_done),
    .ap_continue(Loop_Loop3_proc_U0_ap_continue),
    .ap_idle(Loop_Loop3_proc_U0_ap_idle),
    .ap_ready(Loop_Loop3_proc_U0_ap_ready),
    .tempA2_dout(tempA2_dout),
    .tempA2_empty_n(tempA2_empty_n),
    .tempA2_read(Loop_Loop3_proc_U0_tempA2_read),
    .data_out2_address0(Loop_Loop3_proc_U0_data_out2_address0),
    .data_out2_ce0(Loop_Loop3_proc_U0_data_out2_ce0),
    .data_out2_we0(Loop_Loop3_proc_U0_data_out2_we0),
    .data_out2_d0(Loop_Loop3_proc_U0_data_out2_d0)
);

lab4_z2_fifo_w32_d16_S tempA1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_Loop1_proc_U0_tempA1_din),
    .if_full_n(tempA1_full_n),
    .if_write(Loop_Loop1_proc_U0_tempA1_write),
    .if_dout(tempA1_dout),
    .if_empty_n(tempA1_empty_n),
    .if_read(Loop_Loop2_proc_U0_tempA1_read)
);

lab4_z2_fifo_w32_d16_S tempA2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_Loop1_proc_U0_tempA2_din),
    .if_full_n(tempA2_full_n),
    .if_write(Loop_Loop1_proc_U0_tempA2_write),
    .if_dout(tempA2_dout),
    .if_empty_n(tempA2_empty_n),
    .if_read(Loop_Loop3_proc_U0_tempA2_read)
);

lab4_z2_start_for_Loop_Loop2_proc_U0 start_for_Loop_Loop2_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Loop2_proc_U0_din),
    .if_full_n(start_for_Loop_Loop2_proc_U0_full_n),
    .if_write(Loop_Loop1_proc_U0_start_write),
    .if_dout(start_for_Loop_Loop2_proc_U0_dout),
    .if_empty_n(start_for_Loop_Loop2_proc_U0_empty_n),
    .if_read(Loop_Loop2_proc_U0_ap_ready)
);

lab4_z2_start_for_Loop_Loop3_proc_U0 start_for_Loop_Loop3_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_Loop3_proc_U0_din),
    .if_full_n(start_for_Loop_Loop3_proc_U0_full_n),
    .if_write(Loop_Loop1_proc_U0_start_write),
    .if_dout(start_for_Loop_Loop3_proc_U0_dout),
    .if_empty_n(start_for_Loop_Loop3_proc_U0_empty_n),
    .if_read(Loop_Loop3_proc_U0_ap_ready)
);

assign Loop_Loop1_proc_U0_ap_continue = 1'b1;

assign Loop_Loop1_proc_U0_ap_start = ap_start;

assign Loop_Loop1_proc_U0_start_full_n = (start_for_Loop_Loop3_proc_U0_full_n & start_for_Loop_Loop2_proc_U0_full_n);

assign Loop_Loop2_proc_U0_ap_continue = ap_sync_done;

assign Loop_Loop2_proc_U0_ap_start = start_for_Loop_Loop2_proc_U0_empty_n;

assign Loop_Loop3_proc_U0_ap_continue = ap_sync_done;

assign Loop_Loop3_proc_U0_ap_start = start_for_Loop_Loop3_proc_U0_empty_n;

assign ap_done = ap_sync_done;

assign ap_idle = (Loop_Loop3_proc_U0_ap_idle & Loop_Loop2_proc_U0_ap_idle & Loop_Loop1_proc_U0_ap_idle);

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_ready = Loop_Loop1_proc_U0_ap_ready;

assign ap_sync_done = (Loop_Loop3_proc_U0_ap_done & Loop_Loop2_proc_U0_ap_done);

assign data_in_address0 = Loop_Loop1_proc_U0_data_in_address0;

assign data_in_address1 = 4'd0;

assign data_in_ce0 = Loop_Loop1_proc_U0_data_in_ce0;

assign data_in_ce1 = 1'b0;

assign data_in_d0 = 32'd0;

assign data_in_d1 = 32'd0;

assign data_in_we0 = 1'b0;

assign data_in_we1 = 1'b0;

assign data_out1_address0 = Loop_Loop2_proc_U0_data_out1_address0;

assign data_out1_address1 = 4'd0;

assign data_out1_ce0 = Loop_Loop2_proc_U0_data_out1_ce0;

assign data_out1_ce1 = 1'b0;

assign data_out1_d0 = Loop_Loop2_proc_U0_data_out1_d0;

assign data_out1_d1 = 32'd0;

assign data_out1_we0 = Loop_Loop2_proc_U0_data_out1_we0;

assign data_out1_we1 = 1'b0;

assign data_out2_address0 = Loop_Loop3_proc_U0_data_out2_address0;

assign data_out2_address1 = 4'd0;

assign data_out2_ce0 = Loop_Loop3_proc_U0_data_out2_ce0;

assign data_out2_ce1 = 1'b0;

assign data_out2_d0 = Loop_Loop3_proc_U0_data_out2_d0;

assign data_out2_d1 = 32'd0;

assign data_out2_we0 = Loop_Loop3_proc_U0_data_out2_we0;

assign data_out2_we1 = 1'b0;

assign start_for_Loop_Loop2_proc_U0_din = 1'b1;

assign start_for_Loop_Loop3_proc_U0_din = 1'b1;

endmodule //lab4_z2
