// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_kp_502_15 (
volatile void* r_0,
volatile void* r_1,
volatile void* r_2,
volatile void* r_3,
volatile void* r_4,
volatile void* r_5,
volatile void* r_6,
volatile void* r_7,
volatile void* a_0,
volatile void* a_1,
volatile void* a_2,
volatile void* a_3,
volatile void* a_4,
volatile void* a_5,
volatile void* a_6,
volatile void* a_7,
volatile void* b_0,
volatile void* b_1,
volatile void* b_2,
volatile void* b_3,
volatile void* b_4,
volatile void* b_5,
volatile void* b_6,
volatile void* b_7,
volatile void* c_0,
volatile void* c_1,
volatile void* c_2,
volatile void* c_3,
volatile void* c_4,
volatile void* c_5,
volatile void* c_6,
volatile void* c_7,
volatile void* x_0,
volatile void* x_1,
volatile void* x_2,
volatile void* x_3,
volatile void* x_4,
volatile void* x_5,
volatile void* x_6,
volatile void* x_7);
