// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_lab7_z3 (
volatile void* a_0,
volatile void* a_1,
volatile void* a_2,
volatile void* a_3,
volatile void* a_4,
volatile void* a_5,
volatile void* a_6,
volatile void* a_7,
volatile void* a_8,
volatile void* a_9,
volatile void* a_10,
volatile void* a_11,
volatile void* a_12,
volatile void* a_13,
volatile void* a_14,
volatile void* a_15,
volatile void* b_0,
volatile void* b_1,
volatile void* b_2,
volatile void* b_3,
volatile void* b_4,
volatile void* b_5,
volatile void* b_6,
volatile void* b_7,
volatile void* b_8,
volatile void* b_9,
volatile void* b_10,
volatile void* b_11,
volatile void* b_12,
volatile void* b_13,
volatile void* b_14,
volatile void* b_15,
volatile void* c_0,
volatile void* c_1,
volatile void* c_2,
volatile void* c_3,
volatile void* c_4,
volatile void* c_5,
volatile void* c_6,
volatile void* c_7,
volatile void* c_8,
volatile void* c_9,
volatile void* c_10,
volatile void* c_11,
volatile void* c_12,
volatile void* c_13,
volatile void* c_14,
volatile void* c_15);
