#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_local_deadlock", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("A_0", 256, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("A_1", 256, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("A_2", 256, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("A_3", 256, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("B_0", 256, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("B_1", 256, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("B_2", 256, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("B_3", 256, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("C_0", 256, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("C_1", 256, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("C_2", 256, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("C_3", 256, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("X1_0", 256, hls_out, 12, "ap_vld", "out_data", 1),
	Port_Property("X1_0_ap_vld", 1, hls_out, 12, "ap_vld", "out_vld", 1),
	Port_Property("X1_1", 256, hls_out, 13, "ap_vld", "out_data", 1),
	Port_Property("X1_1_ap_vld", 1, hls_out, 13, "ap_vld", "out_vld", 1),
	Port_Property("X1_2", 256, hls_out, 14, "ap_vld", "out_data", 1),
	Port_Property("X1_2_ap_vld", 1, hls_out, 14, "ap_vld", "out_vld", 1),
	Port_Property("X1_3", 256, hls_out, 15, "ap_vld", "out_data", 1),
	Port_Property("X1_3_ap_vld", 1, hls_out, 15, "ap_vld", "out_vld", 1),
	Port_Property("X2_0", 256, hls_out, 16, "ap_vld", "out_data", 1),
	Port_Property("X2_0_ap_vld", 1, hls_out, 16, "ap_vld", "out_vld", 1),
	Port_Property("X2_1", 256, hls_out, 17, "ap_vld", "out_data", 1),
	Port_Property("X2_1_ap_vld", 1, hls_out, 17, "ap_vld", "out_vld", 1),
	Port_Property("X2_2", 256, hls_out, 18, "ap_vld", "out_data", 1),
	Port_Property("X2_2_ap_vld", 1, hls_out, 18, "ap_vld", "out_vld", 1),
	Port_Property("X2_3", 256, hls_out, 19, "ap_vld", "out_data", 1),
	Port_Property("X2_3_ap_vld", 1, hls_out, 19, "ap_vld", "out_vld", 1),
	Port_Property("D_0", 256, hls_out, 20, "ap_vld", "out_data", 1),
	Port_Property("D_0_ap_vld", 1, hls_out, 20, "ap_vld", "out_vld", 1),
	Port_Property("D_1", 256, hls_out, 21, "ap_vld", "out_data", 1),
	Port_Property("D_1_ap_vld", 1, hls_out, 21, "ap_vld", "out_vld", 1),
	Port_Property("D_2", 256, hls_out, 22, "ap_vld", "out_data", 1),
	Port_Property("D_2_ap_vld", 1, hls_out, 22, "ap_vld", "out_vld", 1),
	Port_Property("D_3", 256, hls_out, 23, "ap_vld", "out_data", 1),
	Port_Property("D_3_ap_vld", 1, hls_out, 23, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "kp_502_7";
